### ISSUE TITLE
The Save Button still generates a new URL on no change

### ISSUE THREAD

**Issue by TanviKumar** [nodebox/seed#12]
The Save Button still generates a new URL even though seed and sketch haven't changed. Perhaps disable the button on saving and allow clicks on seed change and source change?

Will fix this if required.

**Comment by stebanos** [comment]
I am okay with how it is now, I don't want to necessarily inhibit users from making copies. The greyed out and highlighted buttons already make the user aware if it's appropriate to save or not.

**Comment by TanviKumar** [comment]
Alright! Closing this issue then.
