### ISSUE TITLE
Scrolling in editor

### ISSUE THREAD

**Issue by kunal-mohta** [nodebox/seed#14]
![ezgif com-optimize](https://user-images.githubusercontent.com/30414954/36352159-cffc0258-14da-11e8-80a7-b9c71716411c.gif)
Long texts in the editor cause the scrolling bar to go way below the mark.

**Comment by fdb** [comment]
I don't encounter this issue on Chrome / MacOS. What Browser / OS are you using?

**Comment by kunal-mohta** [comment]
Firefox Developer Edition - 59.0b10 (64-bit)

**Comment by fdb** [comment]
Indeed, I can reproduce it. Changing the view scale to 80% shows the correct behavior. Not sure what causes it though.

**Comment by kunal-mohta** [comment]
Maybe integrating to some other code editor as mentioned in #19 will solve this issue automatically.

**Comment by kunal-mohta** [comment]
I guess this is solved, now that you have integrated CodeMirror.

**Comment by fdb** [comment]
The scrolling is still weird in Safari. There's still something wrong with the Flexbox layout, it seems...

![scrolling-safari](https://user-images.githubusercontent.com/8477/36660299-f99f879e-1ad7-11e8-9372-6e1f8bcd1609.png)

**Comment by stebanos** [comment]
I made some changes to the css styling of CodeMirror a couple of days ago, and Safari seems to look fine currently, so I think this is good to close.
