### ISSUE TITLE
Execute asynchronous JavaScript in a tag

### ISSUE THREAD

**Issue by fdb** [nodebox/seed#18]
Currently the JS filter doesn't work with asynchronous JavaScript, returning a Promise object. It would be cool if we could use something like 

```
js("await (await fetch('https://somewebservice.com/api.json")).json()")
```

and e.g. get the image URL back from a JSON request to Flickr.

**Comment by kunal-mohta** [comment]
So the user can have content from any web service by making requests directly from here?

**Comment by stebanos** [comment]
I created a branch asyncjsfilter. It works with [this twitter example](http://seed.emrg.be/sketch/-L6CTA9XVlqOxAACooOy), but the first time it loads the timeout will kick in before the data has fully loaded!

**Comment by kunal-mohta** [comment]
Okay, I will have a look on it.

**Comment by fdb** [comment]
@stebanos That's because the Heroku app is sleeping... 💤
