### ISSUE TITLE
Integrating a code editor like CodeMirror.

### ISSUE THREAD

**Issue by stebanos** [nodebox/seed#19]
The error messages often show that there's an error in a particular line number but we don't have numbered lines. An editor like [CodeMirror](https://codemirror.net) will help.

**Comment by kunal-mohta** [comment]
I tried integrating CodeMirror to the editor, but didn't make any difference, just added `display : none;` property to the `textarea`. 
But I did the same to some other `html` file with a `textarea` and it worked.
My best guess is that rendering the editor like [this](https://github.com/nodebox/seed/blob/master/js/editor.js#L332-L364) interferes with how CodeMirror functions.

**Comment by fdb** [comment]
Actually we use Preact + CodeMirror in another project as well.

**Comment by kunal-mohta** [comment]
Okay I get it now what I was doing wrong :sweat_smile:
