### ISSUE TITLE
Can't type in editor while animation is playing

### ISSUE THREAD

**Issue by fdb** [nodebox/seed#27]
Either:
- Allow typing during animation, live-updating it while it is playing.
- Stop the animation once you start typing

**Comment by kunal-mohta** [comment]
I don't think that typing is disabled when playing animation. It might because of the `requestAnimationFrame` repeatedly calling the `generateString()` which leads to disability of the editor.
In that case, I think stopping the animation would be a more convenient option.

**Comment by stebanos** [comment]
The issue seems to have been resolved. Maybe due to CodeMirror? Closing this.

**Comment by kunal-mohta** [comment]
@stebanos You may close #35 as well then.
