### ISSUE TITLE
Unknown sketch should give 404, not "Cannot read property split of undefined"

### ISSUE THREAD

**Issue by fdb** [nodebox/seed#37]
Wheb loading an unknown sketch we do not get a 404 error but a weird JavaScript error. 

For example try loading this page:

https://seed.emrg.be/sketch/DOESNOTEXIST

The error looks like the following:

<img src='https://shipusercontent.com/8eee8c0d62f03166cb025410d65265cf/Screen%20Shot%202018-02-23%20at%2015.23.16.png' title='Screen Shot 2018-02-23 at 15.23.16.png' width=499>

**Comment by TanviKumar** [comment]
I suppose this can be done by simply checking if it already exists when
going through the URL. Can I take this up?

**Comment by fdb** [comment]
@TanviKumar sure go ahead. However make sure that this is synced to the new HTTP data interface in #29 .

**Comment by TanviKumar** [comment]
Will do!

**Comment by stebanos** [comment]
Fixed in 5c7caf1733
