### ISSUE TITLE
Configurable animation duration / type

### ISSUE THREAD

**Issue by fdb** [nodebox/seed#6]
As a user I want to be able to configure the duration of the animation instead of using the standard duration.

Using simple syntax at the top of the sketch I could set how long the animation would take (in seconds) and how the animation behaves:

```
% duration: 10s
% animation: linear

root:
- <svg ... />
```

Animation types are:
- **linear**: play the animation repeatedly, from beginning to end.
- **bounce**: play the animation forwards, then backwards, repeatedly.
- **once**: play the animation once.

This depends on #4 (preamble syntax).

**Comment by fdb** [comment]
Gifloopcoder implements the animation types using these formulas: https://github.com/bit101/gifloopcoder/blob/master/src/src/app/render/Interpolation.js

**Comment by kunal-mohta** [comment]
I would like to try this issue if not yet solved..
I have read the code base, and realized that you have used `requestAnimationFrame` for the animations.
Several different animation-types can be added when using `requestAnimationFrame` by using some Math expressions and formulas manipulating how animation varies with time as mentioned above by @fdb

**Comment by stebanos** [comment]
Duration setting was implemented in 2a2e9781, but animation type is still open.

**Comment by kunal-mohta** [comment]
Can I try it?

**Comment by stebanos** [comment]
Sure, why not? :)

**Comment by kunal-mohta** [comment]
The editors don't seem to be working on my forked repo 
![screenshot from 2018-02-15 21-24-50](https://user-images.githubusercontent.com/30414954/36266159-dab76af2-1296-11e8-820b-98bc6e3b9f8c.png)

**Comment by fdb** [comment]
Do you see an error message in the Firefox console?

**Comment by kunal-mohta** [comment]
My bad, there was a typo 
I don't how that occurred
Sorry for bothering
